config/routes.rb
Rails.application.routes.draw do
  resources :scrobbles do
    collection do
      post :import_file
      get :import
      delete :delete_all
    end
  end

  root 'scrobbles#index'

end

app/models/scrobble.rb
class Scrobble < ActiveRecord::Base


  def self.import(file)
    # TODO: don't import duplicates

    CSV.foreach(file.path, { :col_sep => "\t", :headers => true }) do |row|
      hold = row.to_hash
      Scrobble.create!({
        time: hold['ISO time'],
        track_name: hold['track name'],
        artist_name: hold['artist name'],
        album_name: hold['album name'],
        application: hold['application'],
        unixtime: hold['unixtime'],
        track_mbid: hold['track mbid'],
        artist_mbid: hold['artist mid'],
        uncorrected_track_name: hold['uncorrected track name'],
        uncorrected_track_mbid: hold['uncorrected track mbid'],
        uncorrected_artist_name: hold['uncorrected artist name'],
        uncorrected_artist_mbid: hold['uncorrected artist mbid'],
        album_mbid: hold['album mbid'],
        album_artist_name: hold['album artist name'],
        album_artist_mbid: hold['album artist mbid']
      })
    end

    # inserts = []
    # CSV.foreach(file.path, {col_sep: "\t", headers: true}) do |row|
    #   hold = row.to_hash
    #   inserts.push "("\
    #                "#{hold['ISO time']},"\
    #                "#{hold['track name']},"\
    #                "#{hold['artist name']},"\
    #                "#{hold['album name']},"\
    #                "#{hold['application']},"\
    #                "#{hold['unixtime']},"\
    #                "#{hold['track mbid']},"\
    #                "#{hold['artist mid']},"\
    #                "#{hold['uncorrected track name']},"\
    #                "#{hold['uncorrected track mbid']},"\
    #                "#{hold['uncorrected artist name']},"\
    #                "#{hold['uncorrected artist mbid']},"\
    #                "#{hold['album mbid']},"\
    #                "#{hold['album artist name']},"\
    #                "#{hold['album artist mbid']}"\
    #                ")"
    #
    # end
    # Scrobble.connection.execute 'INSERT INTO scrobbles ('\
    #                             "time,"\
    #                             "track_name,"\
    #                             "artist_name,"\
    #                             "album_name,"\
    #                             "application,"\
    #                             "unixtime,"\
    #                             "track_mbid,"\
    #                             "artist_mbid,"\
    #                             "uncorrected_track_name,"\
    #                             "uncorrected_track_mbid,"\
    #                             "uncorrected_artist_name,"\
    #                             "uncorrected_artist_mbid,"\
    #                             "album_mbid,"\
    #                             "album_artist_name,"\
    #                             "album_artist_mbid"\
    #                             ') VALUES '\
    #                             "#{inserts.join(", ")}"

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scrobbles_controller.rb
class ScrobblesController < ApplicationController
  before_action :set_scrobble, only: [:show, :edit, :update, :destroy]

  # GET /scrobbles
  # GET /scrobbles.json
  def index
    @scrobbles = Scrobble.all
  end

  # GET /scrobbles/1
  # GET /scrobbles/1.json
  def show
  end

  # GET /scrobbles/new
  def new
    @scrobble = Scrobble.new
  end

  # GET /scrobbles/1/edit
  def edit
  end

  # POST /scrobbles
  # POST /scrobbles.json
  def create
    @scrobble = Scrobble.new(scrobble_params)

    respond_to do |format|
      if @scrobble.save
        format.html { redirect_to @scrobble, notice: 'Scrobble was successfully created.' }
        format.json { render :show, status: :created, location: @scrobble }
      else
        format.html { render :new }
        format.json { render json: @scrobble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scrobbles/1
  # PATCH/PUT /scrobbles/1.json
  def update
    respond_to do |format|
      if @scrobble.update(scrobble_params)
        format.html { redirect_to @scrobble, notice: 'Scrobble was successfully updated.' }
        format.json { render :show, status: :ok, location: @scrobble }
      else
        format.html { render :edit }
        format.json { render json: @scrobble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrobbles/1
  # DELETE /scrobbles/1.json
  def destroy
    @scrobble.destroy
    respond_to do |format|
      format.html { redirect_to scrobbles_url, notice: 'Scrobble was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_all
    byebug
    Scrobble.delete_all
    respond_to do |format|
      format.html {redirect_to scrobbles_url, notice: 'All scrobbles were successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  def import_file
    # TODO: don't import if there is no file. maybe put in the view and not even accept button press
    # byebug
    Scrobble.import(params[:file])
    redirect_to scrobbles_path, notice: 'Scrobbles were successfully imported.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scrobble
      @scrobble = Scrobble.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrobble_params
      params.require(:scrobble).permit(:time, :trackname, :artistname, :albumname, :application)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrobbles_helper.rb
module ScrobblesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Lastfm
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %div{id: 'main-container', class: 'container'}
      %div{class: 'row'}
        %div{class: 'col-xs-2 pull-left'}
          = link_to scrobbles_url do
            %h3 toolbar placeholder
        %div{class: 'col-xs-10'}
          = yield

app/views/scrobbles/_form.html.haml
= form_for(@scrobble) do |f|
  - if @scrobble.errors.any?
    #error_explanation
      %h2
        = pluralize(@scrobble.errors.count, 'error')
        prohibited this scrobble from being saved:
      %ul
        - @scrobble.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :time
    %br/
    = f.date_select :time
  .field
    = f.label :track_name
    %br/
    = f.text_field :track_name
  .field
    = f.label :artist_name
    %br/
    = f.text_field :artist_name
  .field
    = f.label :album_name
    %br/
    = f.text_field :album_name
  .field
    = f.label :application
    %br/
    = f.text_field :application
  %br
  .actions
    = button_tag type: 'submit', class: 'btn btn-primary' do
      Create Scrobble

app/views/scrobbles/edit.html.haml
%h1 Editing Scrobble
= render 'form'
= link_to 'Show', @scrobble
|
= link_to 'Back', scrobbles_path

app/views/scrobbles/import.html.haml
%h1 Import Scrobbles

%p This feature currently only works with the .tsv version of the file

-# TODO: make this work better... submit button,,, click text field for upload... uhh
= form_tag import_file_scrobbles_path, multipart: true do |f|
  %div{class: 'row'}
    %div{class: 'col-xs-12'}
      %div{class: 'input-group'}
        %span{class: 'input-group-btn'}
          %span{class: 'btn btn-inverse btn-file'}
            Browse
            = file_field_tag :file
        %input{type: 'text', class: 'form-control', readonly: true}
  %br
  %div{class: 'row'}
    %div{class: 'col-xs-12'}
      = button_tag type: 'submit', class: 'btn btn-primary pull-right' do
        Import File

-#%br
-#%div{class: 'row'}
-#  %div{class: 'col-xs-12 pull right'}
-#    = submit_tag


-#             <div class="input-group">
                <span class="input-group-btn">
                    <span class="btn btn-primary btn-file">
                        Browse&hellip; <input type="file" multiple>
                    </span>
                </span>
                <input type="text" class="form-control" readonly>


-# doesn't work
-#%div{class: 'row'}
-#  =form_tag import_file_scrobbles_path, multipart: true do |f|
-#    %div{class: 'control-group'}
-#      %div{class: 'attach-set'}
-#        = f.input :real_file, input_html: { hidden: true }, label: 'Upload Attachment'
-#        %div{class: 'input-append'}
-#          %input{id: 'file-display', class: 'input-large uneditable-input', type: 'text'}
-#          = link_to raw(''), id: 'upload-btn', class: 'btn' do
-#            %i{class: 'icon-upload-alt'}
-#            Browse

-# not pretty
-#%div{class: 'row'}
-#  %div{class: 'col-xs-12'}
-#    = form_tag import_scrobbles_path, multipart: true do
-#      = file_field_tag :file
-#      = submit_tag 'Import'

app/views/scrobbles/index.html.haml
%p#notice= notice
%div{class: 'row'}
  %div{class: 'col-xs-7'}
    %h1 Listing Scrobbles
  %div{class: 'col-xs-3'}
    = link_to new_scrobble_path, class: 'btn btn-success', id: 'btn-new-scrobble' do
      New Scrobble &nbsp;
      %i{class: 'glyphicon glyphicon-plus'}
  %div{class: 'col-xs-2'}
    = link_to delete_all_scrobbles_path, method: :delete, data: { confirm: 'Deleting ALL scrobbles! Are you sure?' }, id: 'btn-delete-all', class: 'btn btn-danger btn-md' do
      %i{class: 'glyphicon glyphicon-trash'}
%div{class: 'row'}
  = link_to import_scrobbles_path, class: 'btn btn-success' do
    Import Scrobbles

%div{class: 'row'}
  %table{class: 'table table-hover'}
    %thead
      %tr
        %th Time
        %th Trackname
        %th Artistname
        %th Albumname
        %th Application
        %th
    %tbody
      - @scrobbles.each do |scrobble|
        %tr
          %td= scrobble.time
          %td= scrobble.track_name
          %td= scrobble.artist_name
          %td= scrobble.album_name
          %td= scrobble.application
          %td
            = link_to scrobble, class: 'btn btn-inverse btn-xs' do
              %i{class: 'glyphicon glyphicon-th-list'}
            = link_to edit_scrobble_path(scrobble), class: 'btn btn-inverse btn-xs' do
              %i{class: 'glyphicon glyphicon-edit'}
            = link_to scrobble, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-inverse btn-xs' do
              %i{class: 'glyphicon glyphicon-remove'}

  %br

app/views/scrobbles/new.html.haml
%h1 New Scrobble
= render 'form'
%br
= link_to 'Back', scrobbles_path

app/views/scrobbles/show.html.haml
=# TODO: restrict what user sees?
%p#notice= notice
-#%p
-#  %strong Time:
-#  = @scrobble.time
-#%p
-#  %strong Trackname:
-#  = @scrobble.track_name
-#%p
-#  %strong Artistname:
-#  = @scrobble.artist_name
-#%p
-#  %strong Albumname:
-#  = @scrobble.album_name
-#%p
-#  %strong Application:
-#  = @scrobble.application
- Scrobble.attribute_names.each do |attribute|
  %p
    %strong
      = attribute + ':'
    = eval('@scrobble.' + attribute)

= link_to 'Edit', edit_scrobble_path(@scrobble)
|
= link_to 'Back', scrobbles_path